# SPDX-License-Identifier: GPL-3.0-only
---
# Based on ansible-lint / community.sap_install yamllint config
extends: default

ignore: |
  .ansible/
  .cache/
  .config/
  .github/
  .tox/
  changelogs/
  node_modules/
  venv/
  **/molecule/**

rules:
  braces: {max-spaces-inside: 1, level: error}
  brackets: {max-spaces-inside: 1, level: error}
  comments:
    require-starting-space: false
    min-spaces-from-content: 1
  comments-indentation: disable
  line-length: disable
  truthy: disable
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
